version: '3'
services:
  telegram-monitor-bot:
    build: .
    container_name: telegram_monitor_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./session.txt:/app/session.txt
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('fs').existsSync('./session.txt')"]
      interval: 30s
      timeout: 10s
      retries: 3
